Bootstrap: docker
From: texlive/texlive:latest-full

%post

    echo "Setting environment variables"
    export DEBIAN_FRONTEND=noninteractive

    apt-get update
    apt-get install -y git build-essential

    # Download and install the Metropolis theme
    mkdir -p /usr/share/texlive/texmf-dist/tex/latex/beamer/themes
    cd /usr/share/texlive/texmf-dist/tex/latex/beamer/themes
    git clone https://github.com/matze/mtheme.git metropolis
    cd metropolis
    make sty
    texhash
